### ISSUE TITLE
20190528 (Font | background-image | Architecture components | BEM)

### ISSUE THREAD

**Issue by norvca** [norvca/dailyProgress#58]
### Font with inheritance
We usually set the font and color property in the body tag Because of inheritance
```CSS
body {
  font-family: "Lato", sans-serif;
  font-weight: 400;
  font-size: 16px;
  line-height: 1.7;
  color: #777;
}
```

### Multiple background-image
We can set  multiple background image through comma
```CSS
.header {
  /* A transparent gradient */
  background-image: linear-gradient(
      to right,
      rgba(126, 213, 111, 0.788),
      hsla(160, 64%, 43%, 0.788)
    ),

    /* An image */
    url(../img/hero.jpg);
  background-position: top;

  /*clip the shape we wanted*/
  clip-path: polygon(0 0, 100% 0, 100% 80%, 0 100%);
}
```

### BEM
Naming class with BEM method:

**Block**: Standalone component that is meaningful
**Element**: Part of a block that has no standalone meaning
**Modifier**: A different version of a block or an element

```CSS
.block {}

.block__element {}

.block__element--modifier {}
```

### Architecture
The 7-1 pattern: 7 different folders for partial Sass files, and 1 main Sass file to import all other files
into a compiled CSS file.
```js
// The 7 folders
- base/
- components/
- layout/
- pages/
- themes/
- abstracts/
- venders/
```

> waiting to add more details...
