### ISSUE TITLE
20190615 (Introducing Sass)

### ISSUE THREAD

**Issue by norvca** [norvca/dailyProgress#59]
Sass is a CSS preprocessor, an extension of CSS that adds power and elegance. 

### Variables
We use variables for reusable values such as colors, font-sizes, etc.
Scss: 
```CSS
$color-primary: #777;
$color-white: #fff;

body {
  color: $color-primary;
}
```

CSS:
```CSS
body {
  color: #777;
}
```

### Nesting
Nesting selectors inside of one another, allowing us to write less code.
Scss:

```CSS
.navigation {
  list-style: none;
  
  li {
    display: inline-block;
    margin-left: 10px;
    
    &::first-child {
     margin: 0;
    }
  }
}
```

CSS:
```CSS
.navigation {
  list-style: none;
}

.navigation li {
  display: inline-block;
  margin-left: 10px;
}

.navigation li::first-child {
  margin: 0;
}
```
