### ISSUE TITLE
20190722 (Implement grid system with float) 

### ISSUE THREAD

**Issue by norvca** [norvca/dailyProgress#64]
### Result
![32](https://user-images.githubusercontent.com/20738490/61635774-da734400-acc6-11e9-94ac-f3d86af050e8.png)

### HTML code
```html
  ...
  <body>
    <div class="grid-system">
      <div class="row">
        <div class="col-1-of-2">col-1-of-2</div>
        <div class="col-1-of-2">col-1-of-2</div>
      </div>
      <div class="row">
        <div class="col-1-of-3">col-1-of-3</div>
        <div class="col-1-of-3">col-1-of-3</div>
        <div class="col-1-of-3">col-1-of-3</div>
      </div>
      <div class="row">
        <div class="col-1-of-3">col-1-of-3</div>
        <div class="col-2-of-3">col-2-of-3</div>
      </div>
    </div>
  </body>
  ...
```

### CSS code
```css
// using SASS

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-size: 30px;
}

$gutter-horizontal: 50px;
$gutter-vertical: 30px;

// Avoid parent element collapse
@mixin clearfix {
  &::after {
    content: '';
    display: block;
    clear: both;
  }
}

.row {
  max-width: 1140px;
  margin: 0 auto;
  background-color: #ccc;

  &:not(:last-child) {
    margin-bottom: $gutter-vertical;
  } 

  @include clearfix;  
}


[class^=col-] {
  float: left;
  background-color: #f77;

  &:not(:last-child) {
    margin-right: $gutter-horizontal;
  }
}

.col-1-of-2 {
  width: calc((100% - #{$gutter-horizontal} ) / 2);
}

.col-1-of-3 {
  width: calc((100% - 2 * #{$gutter-horizontal} ) / 3);
}

.col-2-of-3 {
  width: calc(
    (100% - 2 * #{$gutter-horizontal} ) / 3 * 2 + #{$gutter-horizontal}
    );
}
```
