### ISSUE TITLE
20200125 (CSS layout algorithm)

### ISSUE THREAD

**Issue by norvca** [norvca/dailyProgress#82]
> Last update: 2020/1/27

```scss
// Layout algorithm
@mixin layout($width: 4) {
  $columns: 4;
  $initial-basis: percentage($width / $columns);
  // TODO: How do we get this $gap?
  $gap: ($columns - $width) * 1%;
  flex-basis: $initial-basis - $gap;
}

.wrapper {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-between;
}

// Desktop
.box1,
.box2,
.box3,
.box4 {
  @include layout(1);
}

.box5,
.box6 {
  @include layout(2);
}

// Phone
@media only screen and (max-width: 500px) {
  .box1,
  .box2 {
    @include layout(2);
  }

  .box3 {
      @include layout(1);
  }

  .box4 {
    @include layout(3);
  }

  .box5,
  .box6 {
    @include layout(4);
  }
}
```

- Layout in desktop
![1](https://user-images.githubusercontent.com/20738490/73171859-ae84bf80-413c-11ea-9bb6-d71749eca32a.png)

- Layout in phone
![2](https://user-images.githubusercontent.com/20738490/73171867-b17fb000-413c-11ea-9648-9410fbb04f1b.png)
